name = "xmoj-email"
main = "Source/index.ts"
compatibility_date = "2023-08-21"
kv_namespaces = [
    { binding = "XMOJEmailKV", id = "2d8fcff17daa4c45b7699a0f319583e8", preview_id = "ead3c1bf76e242b5a56c934b2e920284" }
]

[[d1_databases]]
binding = "db"
database_name = "xmoj-email"
database_id = "68a1fe1f-5fd1-4a4e-82a2-cb2180d348dd"
