name: "Bug report"
description: "Create a report to help us improve"
labels: bug
assignees: "langningchen"
title: "[BUG] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file an issue! Please fill out the sections below.
  - type: input
    id: title
    attributes:
      label: Issue title
      description: A clear and concise summary of the issue.
      placeholder: ""
      value: ""
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: ""
      value: ""
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: ""
      value: ""
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: ""
      value: ""
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: ""
      value: ""
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: ""
      value: ""
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: ""
      value: ""
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide the following information.
      placeholder: "Browser version: Microsoft Edge Version 117.0.2024.0 (Official build) canary (64-bit)\nOS version: Windows 11 Version 23H2 (OS Build 25921.1000)"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide the following information.
      placeholder: ""
      value: ""
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following items before submitting your issue.
      options:
        - label: I have searched the [issues of this repository](https://github.com/langningchen/XMOJ-Script/issues) and believe that this is not a duplicate.
        - label: I have reproduced the issue with the latest version of the repository.
        - label: I have ensured that the issue is not related to my environment.
        - label: I have read the [Contributor covenant](https://github.com/langningchen/XMOJ-Script/blob/master/CODE_OF_CONDUCT.md).
    validations:
      required: true
