name = "xmoj-bbs"
main = "Source/index.ts"
compatibility_date = "2023-08-17"
kv_namespaces = [
    { binding = "XMOJEmailKV", id = "2d8fcff17daa4c45b7699a0f319583e8", preview_id = "ead3c1bf76e242b5a56c934b2e920284"}
]

[[d1_databases]]
binding = "DB"
database_name = "xmoj-bbs"
database_id = "f70729f0-6ac4-4c31-8bf4-0e1ce18d1fd6"
