name: AutoLabelPR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  AutoLabelPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          dot: true
