name: AutoLabel
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  AutoLabel:
    name: AutoLabel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: AutoLabel
        run: |
          cd ./Update
          npm install
          node ./AutoLabel.js
