name: AutoLabelIssue
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  AutoLabel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Label issue
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - run: |
          cd ./Update
          npm install
          node ./AutoLabel.js ${{ secrets.GITHUB_TOKEN }}
