name: AutoLabelIssue
on:
  issue_comment:
    types:
      - created
      - edited
jobs:
  AutoLabel:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ./Update
          npm install
          node ./AutoLabel.js ${{ secrets.GITHUB_TOKEN }}
