name: Daily
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  DeleteActions:
    runs-on: ubuntu-latest 
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: DeleteActions
        run: |
          echo ${{ steps.generate_token.outputs.token }} | gh auth login --with-token
          for WorkflowRun in $(gh api repos/${{ github.repository }}/actions/runs --paginate -q '.workflow_runs[] | select(.status == "completed") | select(.name | contains("AutoLabelIssue") or contains("AuthLabelPR") or contains("UpdateToRelease") or contains("UpdateVersion")) | "\(.id)"')
          do
            gh api --method DELETE /repos/${{ github.repository }}/actions/runs/$WorkflowRun
          done
  Stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/stale@v8
        with:
          repo-token:  ${{ steps.generate_token.outputs.token }}
          days-before-stale: 7
          exempt-issue-labels: frozen
