name: Daily
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  DeleteActions:
    runs-on: ubuntu-latest
    steps:
      - name: DeleteActions
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          for WorkflowRun in $(gh api repos/${{ github.repository }}/actions/runs --paginate -q '.workflow_runs[] | select(.status == "completed") | select(.name | contains("AutoLabelIssue") or contains("AuthLabelPR") or contains("UpdateToRelease") or contains("UpdateVersion")) | "\(.id)"')
          do
            gh api --method DELETE /repos/${{ github.repository }}/actions/runs/$WorkflowRun
          done
  Stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7
          exempt-issue-labels: frozen
