name: DeleteActions
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  DeleteActions:
    name: DeleteActions
    runs-on: ubuntu-latest
    steps:
      - name: DeleteActions
        run: gh api repos/langningchen/XMOJ-Script/actions/runs --paginate -q '.workflow_runs[] | "\(.id)"' | xargs -n1 -I % gh api --method DELETE /repos/langningchen/XMOJ-Script/actions/runs/%
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
