name: Deploy only
on:
  workflow_dispatch:
permissions:
    id-token: write
    contents: write
    pages: write
    deployments: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Version
        id: get_version
        run: echo "version=$(cat XMOJ.user.js | grep -oP '(?<=@version)\s*.*' | tr -d ' ')" >> $GITHUB_ENV
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Push new version
        run: |
          git config --global user.name "langningchen"
          git config --global user.email "jpxx_chenlangning@outlook.com"
          git add .
          git commit -m "Update version to ${{ steps.get_version.outputs.version }}"
          git push
