name: PRAutoclose
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Close PRAutoclose
      run: |
        if [[ ${{ github.event.pull_request.head.ref }} != "dev" ]]; then
          echo "Closing PR"
          gh pr comment ${{ github.event.pull_request.number }} --body "请向\`dev\`分支提交pull request, 本pull request将被自动关闭"
          gh pr close ${{ github.event.pull_request.number }}
        else
          echo "Not closing PR"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
