name: PRAutoclose
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Close PRAutoclose
      run: |
        if [[ ${{ github.event.pull_request.base.ref }} != "dev" ]]; then
          echo "Closing PR"
          gh pr close ${{ github.event.pull_request.number }} --delete-branch
        else
          echo "Not closing PR"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
