name: Prerelease
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  Prerelease:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: node ./Update/GetVersion.js
      - id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          draft: false
          prerelease: true
          files: XMOJ.user.js
          target_commitish: ${{ github.sha }}
      - name: Bump npm version
        run: |
          cd Server
          npm version from-git
          git config --global user.email "thomas_rainbowfish@icloud.com"
          git config --global user.name "boomzero"
          git checkout -b actions/temp
          git add *
          git commit -m "update npm version"
          git push -f
          gh pr create -B "Dev" -t "update npm version"
          
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: .
      - uses: actions/deploy-pages@v2
