name: Prerelease
on:
  push:
    branches:
      - dev
    paths:
      - XMOJ.user.js
  workflow_dispatch:
jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0
      - name: Update Version
        id: update_version
        run: node Update.js
      - name: Create Prerelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.update_version.outputs.version }}
          release_name: ${{ steps.update_version.outputs.version }}
          prerelease: true
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: XMOJ.user.js
          asset_name: XMOJ.user.js
          asset_content_type: application/javascript
      - name: Commit
        run: |
          git config --local user.email "jpxx_chenlangning@outlook.com"
          git config --local user.name "Chen Langning"
          git remote set-url origin "https://chenlangning:${{ secrets.PAT_TOKEN }}@github.com/chenlangning/XMOJ-Script.git
          git checkout dev
          git commit -a -m "Update version to ${{ steps.update_version.outputs.version }}"
          git push origin dev
