name: Generate xml sitemap

on:
  push:
    branches: [ dev ]
jobs:
  UpdateVersion:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate new sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1.6.1
      with:
        base-url-path: https://xmoj-bbs.tech/
        exclude-paths: /404.html
    - name: Push sitemap to repository
      run: |
        git remote set-head origin dev
        git config --global user.name "hendragon-bot[bot]"
        git config --global user.email "hendragon-bot[bot]@users.github.com"
        git add sitemap.xml
        git commit -m "更新 sitemap [ 自动 ]"
        git push
