name: UpdateToRelease
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
jobs:
  UpdateToRelease:
    name: UpdateToRelease
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update to release
        run: node ./Update/UpdateToRelease.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.number }}
