name: UpdateVersion
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - dev
jobs:
  UpdateVersion:
    name: UpdateVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version
        id: update_version
        run: node ./Update/UpdateVersion.js ${{ github.event.number }} ${{ github.event.pull_request.title }}
