name: UpdateVersion
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - dev
jobs:
  UpdateVersion:
    name: UpdateVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check branch
        run: |
          git fetch origin master
          git diff --name-only master | grep -q "Update/UpdateVersion.js"
          if [ $? -eq 0 ]; then
            # echo "UpdateVersion.js has been changed in master branch, please merge master branch to dev branch first."
            gh pr comment ${{ github.event.pull_request.number }} --body "您的分支 \`${{ github.event.pull_request.head.ref }}\` 已经落后于 \`Dev\` 分支，请先合并 \`Dev\` 分支到您的分支。"
            exit 1
          fi
      - name: Update version
        id: update_version
        run: node ./Update/UpdateVersion.js
      - name: Commit files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Update version info to ${{ steps.update_version.outputs.version }}"
          git push
