name: UpdateVersion
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev
  push:
    branches:
      - dev
    paths:
      - XMOJ.user.js
  workflow_dispatch:
jobs:
  UpdateVersion:
    name: UpdateVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Update version
        id: update
        run: node Update.js
      - name: Commit files
        run: |
          git config --local user.email "jpxx_chenlangning@outlook.com"
          git config --local user.name "Langning Chen"
          git commit -a -m "Update version to ${{ steps.update.outputs.version }}"
          git push
