on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - dev
jobs:
  UpdateVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version
        run: node ./Update/UpdateVersion.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.number }} "${{ github.event.pull_request.title }}"
