name: UpdateToRelease
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
jobs:
  UpdateToRelease:
    name: UpdateToRelease
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update to release
        id: update_to_release
        run: node ./Update/UpdateToRelease.js
      - name: Commit files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Update version info to ${{ steps.update_to_release.outputs.version }}"
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Upload to GitHub
        uses: LasyIsLazy/github-upload-action@v0.1.0
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: dev
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          file-path: ./Update.json
