name: UpdateToRelease
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
jobs:
  UpdateToRelease:
    name: UpdateToRelease
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout PR
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update to release
        id: update_to_release
        run: node ./Update/UpdateToRelease.js
      - name: Config git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Create branch
        run: |
          git checkout -b actions/temp
          git add .
          git commit -m "Update version info to ${{ steps.update_to_release.outputs.version }}"
          git push origin actions/temp
      - name: Create PR
        run: gh pr create --title "Update to release ${{ steps.update_to_release.outputs.version }}" --body "Update to release ${{ steps.update_to_release.outputs.version }}" --base dev --head actions/temp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        run: gh pr merge ${{ github.event.number }} --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete PR
        run: gh pr delete ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete branch
        run: git push origin --delete actions/temp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
